dev:
  children:
    webservers:
      hosts:
        ubuntu-01:
          ansible_host: 192.168.56.101
        ubuntu-02:
          ansible_host: 192.168.56.102
    loadbalancers:
      hosts:
        ubuntu-03:
          ansible_host: 192.168.56.103

local:
  children:
    my_pc:
      hosts:
        master_ansible:
          ansible_host: localhost
          ansible_connection: local
