--- # setup-lb.yml

- hosts: ubuntu-01
  become: yes
  tasks:
    - name: Pobieramy conf z webserver
      fetch:
        src: /etc/apache2/sites-available/000-default.conf
        dest: ../fetched/
        flat: yes

- hosts: loadbalancers
  become: yes
  tasks:
    - name: Przesyłamy conf na lb
      copy:
        src: ../fetched/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        mode: 644