--- # install-services.yml

- name: Instalacja serwisów na LB.
  hosts: loadbalancers
  become: true
  tasks:
    - name: instalacja apache
      apt:
        name: apache2
        state: present # latest - zaktualizuje jeśli jest zainstalowany, absent - odinstaluje
    - name: Autostart apache2
      service:
        name: apache2
        state: started
        enabled: yes

- name: Instalacja serwisów na Web.
  hosts: webservers
  become: yes
  tasks:
    - name: instalacja apache
      apt:
        name: 
          - apache2
          - php
        state: present
    - name: Autostart apache2
      service:
        name: apache2
        state: started
        enabled: yes