--- # setup-lb.yml

- hosts: loadbalancers
  become: yes
  tasks:

  - name: Creating template
    template:
      src: ../config/lb-config.j2
      dest: /etc/apache2/sites-available/000-default.conf
      owner: root
      group: root
      mode: 644

  - name: Restart apache2
    service:
      name: apache2
      state: restarted