--- # setup-app-v2.yml

- name: Ustawiamy naszą aplikację
  hosts: webservers
  become: yes
  vars:
    path_to_app: "/var/www/html/"
    path_to_php_conf_file: "/etc/php/7.4/apache2/php.ini"

  tasks:

    - name: Przesyłamy nasz index.php
      copy:
        src: ../index.php
        dest: "{{ path_to_app }}"
        mode: 0755

    - name: Zamień na nazwę danego hosta
      replace:
        path: "{{ path_to_app }}index.php"
        regexp: 'HOST'
        replace: " {{ inventory_hostname }}"

    - name: Stworzenie strony informacyjnej
      copy:
        dest: "{{ path_to_app }}info.php"
        content: "<h1> Info o hoście: {{ ansible_hostname }} </h1>"

    - name: Pokaż zawartośc folderu /var/www/html/
      command: ls -la {{ path_to_app }}
      register: dir_content

    - name: Debug
      debug: 
        msg: "{{ dir_content }}"

    - name: Konfiguracja pliku php.ini
      lineinfile:
        path: "{{ path_to_php_conf_file }}"
        regexp: ^short_open_tag
        line: 'short_open_tag=On'
      notify: Restart apache

  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted